- zera-basemodule/CMakeLists.txt
- zera-comm/zera-i2c/CMakeLists.txt
- zera-comm/zera-proxy/CMakeLists.txt
- zera-dev/CMakeLists.txt
- zera-math/CMakeLists.txt
- zera-misc/CMakeLists.txt
- zera-modules/interface/CMakeLists.txt
- zera-validator/CMakeLists.txt
- zera-xml-config/CMakeLists.txt
Signed-off-by: bhamacher <b.hamacher@zera.de>
> library namespaces fixed

- zera-basemodule/regexvalidator.cpp
- zera-modules/statusmodule/src/statusmoduleinit.cpp
* Check for reg-expression match
* Statusmodule: Change regexpression. Tested at [1] and zera-setup2
[1] https://regexr.com/
> statusmodule: rework RegEx Handling

- CMakeLists.txt
- zera-dev/zera_mcontroller_base.cpp
- zera-dev/zera_mcontroller_base.h
- zera-mcontroller-io/CMakeLists.txt
- zera-mcontroller-io/main.cpp
- zera-misc/intelhexfileio.cpp
- zera-misc/intelhexfileio.h
- zera-misc/intelhexfileio_p.cpp
- zera-misc/intelhexfileio_p.h
Patches 1-4: cleanup/enhancements to prepare
Patch 5: The command line tool 'zera-mcontroller-io'
Tests:
* hardware commands: no issues yet
* bootloader commands: no success yet but my suspicion is there is no bootloader...
> Rework boot: create commandline tool 'zera-mcontroller-io'

- zera-modules/sec1module/src/mt310s2-sec1module.xml
- zera-modules/sec1module/src/sec1module.xsd
- zera-modules/sec1module/src/sec1moduleconfigdata.h
- zera-modules/sec1module/src/sec1moduleconfiguration.cpp
- zera-modules/sec1module/src/sec1moduleconfiguration.h
- zera-modules/sec1module/src/sec1modulemeasprogram.cpp
- zera-modules/sec1module/src/sec1modulemeasprogram.h
Added code for modules rating of measurement results.
> Master sec test

- zera-modules/rangemodule/src/rangemeaschannel.cpp
- zera-modules/statusmodule/src/statusmoduleinit.cpp
- zera-modules/statusmodule/src/statusmoduleinit.h
Commit 1: Just silence some warnings
Commit 2: Add a statusmachine to re-read adjustment-status
Commit 3: Register and unregister notification / start re-read.statusmachine in case of notification
> Clamp hotplug adj status

- zera-modules/sec1module/src/sec1modulemeasprogram.cpp
- zera-modules/sec1module/src/sec1modulemeasprogram.h
> sec1/multi: Introduce error range calculation

- zera-modules/rangemodule/src/com5003-rangemodule.xml
- zera-modules/rangemodule/src/com5003-rangemoduleREF.xml
- zera-modules/rangemodule/src/mt310s2-rangemodule.xml
- zera-modules/rangemodule/src/rangemeaschannel.cpp
- zera-modules/rangemodule/src/rangemeaschannel.h
- zera-modules/rangemodule/src/rangemodule.xsd
- zera-modules/rangemodule/src/rangemoduleconfigdata.h
- zera-modules/rangemodule/src/rangemoduleconfiguration.cpp
- zera-modules/rangemodule/src/rangemoduleconfiguration.h
- zera-modules/rangemodule/src/rangeobsermatic.cpp
- zera-modules/rangemodule/src/rangeobsermatic.h
* Fix nan for clamps plugged / switch off / unplug clamps / switch on
* Remove dangerous configure options
> Range modul fixes

- zera-modules/rangemodule/src/rangeobsermatic.cpp
The components have validators but do not do anything yet.
Signed-off-by: bhamacher <b.hamacher@zera.de>
> Add components for U and I transformer

- zera-modules/statusmodule/src/statusmoduleinit.cpp
- zera-modules/statusmodule/src/statusmoduleinit.h
The information is extracted from dumped VARSOM-EEPROM file
> statusmodule: Add component INF_CpuInfo

- zera-modules/lambdamodule/src/com5003-lambdamodule.xml
> com5003-lambdamodule: Add necessary bits for 'sum'-lambda

- .github/workflows/buildAndTest.yml
- .github/workflows/triggerMetaUpdates.yml
build on pull request
update zera-metaproject on push
Signed-off-by: bhamacher <b.hamacher@zera.de>
> Add basic CI to zera-classes

- zera-modules/sourcemodule/deviceinfo/FG4PhaseTest.json
- zera-modules/sourcemodule/deviceinfo/MT3000.json
- zera-modules/sourcemodule/deviceinfo/MT400-20.json
> sourcemodule: rename Count[UI]Phases -> [UI]PhaseMax

- zera-modules/sourcemodule/deviceinfo/FG4PhaseTest.json
- zera-modules/sourcemodule/deviceinfo/MT3000.json
- zera-modules/sourcemodule/deviceinfo/MT400-20.json
> sourcemodule/deviceinfo: Introduce per step sizes for client validation

- zera-modules/sourcemodule/src/sourcemoduleprogram.cpp
* We want to build a snapshot to get some feedback without playing tricks on
vf-debugger
* This commit will be reverted as follow up
> sourcemoduleprogram: Hard code demo source count to 4

- zera-modules/sourcemodule/src/sourceinterface.cpp
- zera-modules/sourcemodule/src/sourceinterface.h
- zera-modules/sourcemodule/tests/unittest-sourceinterface.cpp
> sourcemodule: Add IO interface base classes & tests

- zera-modules/sourcemodule/src/sourcedevice.cpp
- zera-modules/sourcemodule/src/sourcedevice.h
- zera-modules/sourcemodule/src/sourcedevicemanager.cpp
- zera-modules/sourcemodule/src/sourcedevicemanager.h
- zera-modules/sourcemodule/src/sourcemoduleprogram.cpp
- zera-modules/sourcemodule/src/sourcemoduleprogram.h
> sourcemodule: Rework error messaging to support errors on source close

- zera-modules/electronicburdenmodule/.gitignore
> electronicburdenmodule/.gitignore: Adjust to CMake

- zera-modules/rangemodule/src/adjustment.cpp
- zera-modules/rangemodule/src/adjustment.h
- zera-modules/rangemodule/src/rangemeaschannel.cpp
- zera-modules/rangemodule/src/rangemeaschannel.h
- zera-modules/rangemodule/src/rangemodule.cpp
- zera-modules/rangemodule/src/rangemodule.h
- zera-modules/rangemodule/src/rangeobsermatic.cpp
- zera-modules/rangemodule/src/rangeobsermatic.h
Acceptance tests are still missing.
For reverts search:
Ticket 409
> Seems to fix scaling issues 

- zera-modules/electronicburdenmodule/src/electronicburdenmoduleprogram.cpp
- zera-modules/electronicburdenmodule/src/electronicburdenmoduleprogram.h
Signed-off-by: Wilfried Schunk <w.schunk@zera.de>
> electronicburdenmodule: add demo component

- zera-modules/sourcemodule/src/sourcedevicevein.cpp
> sourcedevicevein: Do not  propagate last load in case of error

- zera-basemodule/jsonparamvalidator.cpp
- zera-basemodule/jsonparamvalidator.h
- zera-modules/rangemodule/tests/unittest-topics-structure.cpp
- zera-modules/sourcemodule/src/jsonstructureloader.cpp
- zera-modules/sourcemodule/tests/unittest-deviceinfo.cpp
- zera-modules/sourcemodule/tests/unittest-jsonstructureloader.cpp
- zera-modules/sourcemodule/tests/unittest-sourcejsonapi.cpp
> zera-basemodule/sourcemodule: Follow zera-json-helper's API changes

- zera-modules/electronicburdenmodule/deviceinfo/ESVB.json
- zera-modules/electronicburdenmodule/src/electronicburdendevicevein.cpp
- zera-modules/electronicburdenmodule/src/electronicburdendevicevein.h
- zera-modules/electronicburdenmodule/src/electronicburdenmoduleprogram.cpp
- zera-modules/electronicburdenmodule/src/electronicburdenmoduleprogram.h
- zera-modules/electronicburdenmodule/src/veininterface.cpp
- zera-modules/electronicburdenmodule/src/veininterface.h
Signed-off-by: Wilfried Schunk <w.schunk@zera.de>
> electronicburdenmodule : Add burdentypes / vein json components

- zera-modules/sourcemodule/CMakeLists.txt
- zera-modules/sourcemodule/src/io-device/iotransferdatagroup.cpp
- zera-modules/sourcemodule/src/io-device/iotransferdatagroup.h
- zera-modules/sourcemodule/src/io-ids/ioidgenerator.cpp
- zera-modules/sourcemodule/src/io-ids/ioidgenerator.h
- zera-modules/sourcemodule/src/io-queue/iogroupgenerator.cpp
- zera-modules/sourcemodule/src/io-queue/ioqueue.cpp
- zera-modules/sourcemodule/src/io-queue/ioqueue.h
- zera-modules/sourcemodule/src/source-device/sourcedevice.cpp
- zera-modules/sourcemodule/src/source-device/sourcedevice.h
- zera-modules/sourcemodule/src/source-device/sourcedevicebase.cpp
- zera-modules/sourcemodule/src/source-device/sourcedevicestatuswatcherjson.cpp
- zera-modules/sourcemodule/tests/gtest/unittest-ioidgenerator.cpp
- zera-modules/sourcemodule/tests/gtest/unittest-iopacketgenerator.cpp
- zera-modules/sourcemodule/tests/qtest/qt-unittest-ioqueue.cpp
- zera-modules/sourcemodule/tests/qtest/qt-unittest-ioqueue.h
- zera-modules/sourcemodule/tests/qtest/qt-unittest-iotransferdata.cpp
- zera-modules/sourcemodule/tests/qtest/qt-unittest-iotransferdata.h
- zera-modules/sourcemodule/tests/qtest/qt-unittest-sourcedevice.cpp
- zera-modules/sourcemodule/tests/qtest/qt-unittest-sourcedevicestatuswatcherjson.cpp
- zera-modules/sourcemodule/tests/qtest/qt-unittest-sourcedevicestatuswatcherjson.h
- zera-modules/sourcemodule/tests/qtest/sigslotiotransfergroup-forunittest.cpp
- zera-modules/sourcemodule/tests/qtest/sigslotiotransfergroup-forunittest.h
- zera-modules/sourcemodule/tests/qtest/sourcedevice-forunittest.cpp
- zera-modules/sourcemodule/tests/qtest/sourcedevice-forunittest.h
> sourcemodule: Protect data / add tests on IoTransferDataGroup and more

- zera-modules/sourcemodule/tests/qtest/main-unittest-qt.h
- zera-modules/sourcemodule/tests/qtest/qt-unittest-iodevice.cpp
- zera-modules/sourcemodule/tests/qtest/qt-unittest-ioqueue.cpp
- zera-modules/sourcemodule/tests/qtest/qt-unittest-iotransferdata.cpp
- zera-modules/sourcemodule/tests/qtest/qt-unittest-sourcedevicemanager.cpp
- zera-modules/sourcemodule/tests/qtest/qt-unittest-sourceio.cpp
- zera-modules/sourcemodule/tests/qtest/qt-unittest-sourcescanner.cpp
- zera-modules/sourcemodule/tests/qtest/qt-unittest-sourcestatecontroller.cpp
- zera-modules/sourcemodule/tests/qtest/qt-unittest-sourceswitchjson.cpp
> sourcemodule: speed up qtests / use common value for short QTest::qWait

- zera-modules/sourcemodule/CMakeLists.txt
- zera-modules/sourcemodule/src/module-gluelogic/sourcemodule.cpp
- zera-modules/sourcemodule/tests/gtest/unittest-main.cpp
- zera-modules/sourcemodule/tests/qtest/main-unittest-qt.cpp
> sourcemodule: Move qt-resources to static library only

- zera-modules/sourcemodule/src/source-device/sourcedevicemanager.cpp
- zera-modules/sourcemodule/tests/qtest/qt-unittest-sourcedevicemanager.cpp
- zera-modules/sourcemodule/tests/qtest/qt-unittest-sourcedevicemanager.h
Wow: We forgot this important test case causing modulemanager to crash!
> sourcemodule: Fix scanner not finding a source

- zera-modules/modemodule/src/modemoduleinit.cpp
- zera-modules/rangemodule/src/adjustment.cpp
> modemodule/rangemodule: Tidy up code a bit

- zera-comm/zera-i2c/i2cutils.cpp
- zera-comm/zera-i2c/i2cutils.h
We used this code when implementing EMOB firmware update by using i2c-tools
> zera-i2c: Introduce I2cPing

- CMakeLists.txt
- zera-comm/zera-i2c-ping/CMakeLists.txt
- zera-comm/zera-i2c-ping/main.cpp
It seems I2cPing method introduced recently does not work as expected. To make
it testable on target an maybe for later use create a simple cli around I2cPing
> Introduce zera-i2c-ping

- zera-i2c/i2cmuxer.h
- zera-i2c/i2cmuxerinterface.h
> Generalize i2c-muxer by creating a common interface

- zera-modules/sourcemodule/src/source-device/sourcedevicemanager.cpp
- zera-modules/sourcemodule/src/source-device/sourceproperties.cpp
- zera-modules/sourcemodule/src/source-device/sourceproperties.h
- zera-modules/sourcemodule/src/source-scanner/sourcescanner.cpp
- zera-modules/sourcemodule/src/source-scanner/sourcescanneriodemo.cpp
- zera-modules/sourcemodule/src/source-scanner/sourcescanneriozeraserial.cpp
- zera-modules/sourcemodule/tests/gtest/unittest-sourcescannerio.cpp
- zera-modules/sourcemodule/tests/qtest/test_globals.h
- zera-modules/sourcemodule/tests/qtest/test_sourcedevicefacade.cpp
- zera-modules/sourcemodule/tests/qtest/test_sourcedevicemanager.cpp
- zera-modules/sourcemodule/tests/qtest/test_sourcedevicemanager.h
- zera-modules/sourcemodule/tests/qtest/test_sourceio.cpp
- zera-modules/sourcemodule/tests/qtest/test_sourceperiodicpollerstate.cpp
- zera-modules/sourcemodule/tests/qtest/test_sourcescanner.cpp
- zera-modules/sourcemodule/tests/qtest/test_sourcestatecontroller.cpp
- zera-modules/sourcemodule/tests/qtest/test_sourceswitchjson.cpp
Document expected behavior more precise
> test_sourcedevicemanager: Split close-all tests up

- zera-modules-common/zera-basemodule/veinmodulecomponent.cpp
- zera-modules-common/zera-basemodule/veinmodulecomponent.h
- zera-modules/sourcemodule/tests/qtest/test_sourcedevicefacade.cpp
- zera-modules/sourcemodule/tests/qtest/veincomponentsetnotifier-forunittest.cpp
- zera-modules/sourcemodule/tests/qtest/veincomponentsetnotifier-forunittest.h
> Prepare VeinComponentSetNotifier to support multiple entities

- zera-modules/sec1module/src/com5003-sec1module.xml
- zera-modules/sec1module/src/com5003-sec1module2.xml
- zera-modules/sec1module/src/com5003-sec1module3.xml
- zera-modules/sec1module/src/mt310s2-sec1module.xml
- zera-modules/sec1module/src/mt310s2-sec1module_f1f0.xml
- zera-modules/sec1module/src/sec1module.xsd
- zera-modules/sec1module/src/sec1moduleconfigdata.h
- zera-modules/sec1module/src/sec1moduleconfiguration.cpp
- zera-modules/sec1module/src/sec1moduleconfiguration.h
- zera-modules/sec1module/src/sec1modulemeasprogram.cpp
> sec1module: Make DUT constant unit persistent

- zera-modules/sec1module/src/sec1modulemeasprogram.cpp
> sec1modulemeasprogram: Remove orphaned test code

- zera-modules/sec1module/src/multipleresulthelper.cpp
> multipleresulthelper: Add missing include

- zera-modules/rangemodule/src/rangemodulemeasprogram.cpp
> rangemodulemeasprogram: Do not start DSP watchdog in demo mode

- zera-modules/scpimodule/src/scpiinterfacedelegate.h
- zera-modules/scpimodule/src/scpimeasuredelegate.h
- zera-modules/scpimodule/src/scpiparameterdelegate.h
- zera-modules/scpimodule/src/scpipropertydelegate.h
- zera-modules/scpimodule/src/scpistatusdelegate.h
> Add some overrides to cSCPIDelegate inheritants

- zera-modules-common/service-interfaces/lib/CMakeLists.txt
- zera-xmlconfig/lib/CMakeLists.txt
> Move all include files in sub-folder zera-classes

- zera-timers/lib/periodictimerqt.cpp
- zera-timers/lib/periodictimerqt.h
- zera-timers/lib/zeratimerfactorymethods.cpp
- zera-timers/lib/zeratimerfactorymethods.h
- zera-timers/testlib/periodictimertest.cpp
- zera-timers/testlib/periodictimertest.h
- zera-timers/testlib/realdelaytimerhelpers.cpp
- zera-timers/testlib/realdelaytimerhelpers.h
- zera-timers/testlib/timerrunnerfortest.cpp
- zera-timers/testlib/timertestdefaults.h
- zera-timers/testlib/zeratimerfactorymethodstest.cpp
- zera-timers/tests/CMakeLists.txt
- zera-timers/tests/test_periodictimerqt.cpp
- zera-timers/tests/test_periodictimerqt.h
- zera-timers/tests/test_singleshottimer.cpp
- zera-timers/tests/test_singleshottimer.h
Signed-off-by: Anuja Mutalik <a.mutalik@zera.de>
> Introduce PeriodicTimerTest

- zera-modules-common/module-tasks/tests/pcb-server/test_taskchannelgetalias.cpp
- zera-modules-common/module-tasks/tests/pcb-server/test_taskchannelgetovrejection.cpp
- zera-modules-common/module-tasks/tests/pcb-server/test_taskchannelgetrangelist.cpp
- zera-modules-common/module-tasks/tests/pcb-server/test_taskchannelgetrejection.cpp
- zera-modules-common/module-tasks/tests/pcb-server/test_taskchannelgeturvalue.cpp
- zera-modules-common/module-tasks/tests/pcb-server/test_taskchannelregisternotifier.cpp
- zera-modules-common/module-tasks/tests/pcb-server/test_taskunregisternotifier.cpp
- zera-modules-common/module-tasks/tests/resman/test_taskrmchannelscheckavail.cpp
- zera-modules-common/module-tasks/tests/resman/test_taskrmchannelsgetavail.cpp
- zera-modules-common/module-tasks/tests/resman/test_taskrmcheckresourcetype.cpp
- zera-modules-common/module-tasks/tests/resman/test_taskrmsendident.cpp
- zera-modules-common/module-tasks/tests/test_taskfortest.cpp
- zera-modules-common/module-tasks/tests/test_taskservertransactiontemplate.cpp
- zera-modules-common/service-interfaces/testlib/pcbinitfortest.cpp
- zera-modules-common/service-interfaces/testlib/pcbinitfortest.h
- zera-modules-common/service-interfaces/testlib/rminitfortest.cpp
- zera-modules-common/service-interfaces/testlib/rminitfortest.h
> Follow renames in zera-core

- zera-modules/statusmodule/src/statusmoduleinit.cpp
- zera-modules/statusmodule/src/statusmoduleinit.h
statusmodule has no resources to offer
> statusmodule: Do not ident to resourcemanger

- zera-modules/modules/dftmodule/src/dftmodulemeasprogram.cpp
DFT is context. So don't repeat ourselves.
> dftmodule: Shorten some component descriptions

- modulemanager/sessions/com5003-perphase-session.json
This one was in zera-modulemanager already but got lost by not merging latest into zera-classes.
> com5003-perphase-session: Change to fix lambda-module

- modules/modules/sourcemodule/src/module-gluelogic/sourcemoduleprogram.cpp
- modules/modules/sourcemodule/src/module-gluelogic/sourcemoduleprogram.h
Do not assume everybody knows that demo makes creation of m_pVeinDemoSourceCount conditional on m_pModule->m_demo
> sourcemodule: Enhance check on vein source demo count

- modulemanager/loggerconfigs/mt310s2-dc-session-dev.json
It is a blind copy of mt310s2-dc-session.json
> Modulemanager add mt310s2-dc-session-dev.json

- modulemanager/src/modulemanager.h
It just makes it close to impossible to see what's going on :(
> ModuleManager: Get rid of doxygen noise

- .github/workflows/buildAndTest.yml
We are going to use this as template for other repos
> buildAndTest.yml: add main branch

- .github/workflows/buildCachedAndTest.yml
install artifacts are created on all runs of metaproject
> buildCachedAndTest.yml remove thinko

- .github/workflows/buildCachedAndTest.yml
> buildCachedAndTest.yml: Reduce artefact retention time to one say

- CMakeLists.txt
- modulemanager/app/main.cpp
- modulemanager/lib/customerdatasystem.cpp
- modulemanager/lib/customerdatasystem.h
- modulemanager/lib/jsonsessionloader.cpp
- modulemanager/lib/jsonsessionloader.h
- modulemanager/lib/licensesystem.cpp
- modulemanager/lib/licensesystem.h
- modulemanager/lib/moduleeventhandler.cpp
- modulemanager/lib/moduleeventhandler.h
- modulemanager/lib/modulemanager.cpp
- modulemanager/lib/modulemanager.h
- modulemanager/lib/priorityarbitrationsystem.cpp
- modulemanager/lib/priorityarbitrationsystem.h
- modulemanager/lib/zeradblogger.cpp
- modulemanager/lib/zeradblogger.h
- modulemanager/testlib/jsonsessionloadertest.cpp
- modulemanager/testlib/jsonsessionloadertest.h
- modulemanager/testlib/modulemanagerconfigtest.cpp
- modulemanager/testlib/modulemanagertest.cpp
- modulemanager/testlib/modulemanagertest.h
- modulemanager/tests/CMakeLists.txt
- modulemanager/tests/test_modman_config.cpp
- modulemanager/tests/test_modman_session.cpp
- modulemanager/tests/test_modman_session.h
- modules/modules/CMakeLists.txt
- modules/modules/scpimodule/lib/scpimeasure.cpp
- modules/modules/scpimodule/lib/scpimeasure.h
This reverts commit fb115a49c54db66e3b0f13e7e17e3613da66704e.
> Revert "modulemanager: Disable test_modman_session"

- modules/modules/power1module/lib/power1modulemeasprogram.cpp
Currently it's under SENSE model.
> power1modulemeasprogram: Add CATALOG command for measurement mode

- modules/modules/scpimodule/lib/CMakeLists.txt
- modules/modules/scpimodule/lib/delegates/scpimeasuredelegate.cpp
- modules/modules/scpimodule/lib/delegates/scpiparameterdelegate.cpp
- modules/modules/scpimodule/lib/delegates/scpipropertydelegate.cpp
- modules/modules/scpimodule/lib/interfaceinterface.cpp
- modules/modules/scpimodule/lib/scpi-clients/scpiclient.cpp
- modules/modules/scpimodule/lib/scpieventsystem.cpp
Yet another nasty Surprise: Did not expect non conform ZSCPI so widely used in here...
> scpimodule: Use ZSCPI from zenux-services

- modulemanager/scpi-doc/CMakeLists.txt
We intend to execute this from github workflow.
Signed-off-by: Anuja Mutalik <a.mutalik@zera.de>
> scpi-doc/CMakeLists: Install the executable

- .github/workflows/generateScpiDocs.yml
* Under development
* Currently triggered only on 'workflow_dispatch'
> Add generateScpiDocs.yml

- modules/burden1module/lib/burden1measdelegate.h
- modules/burden1module/lib/burden1module.h
- modules/burden1module/lib/burden1moduleconfiguration.cpp
- modules/burden1module/lib/burden1moduleconfiguration.h
- modules/burden1module/lib/burden1modulemeasprogram.cpp
- modules/burden1module/lib/burden1modulemeasprogram.h
- modules/lambdamodule/lib/lambdacalculator.h
- modules/lambdamodule/lib/lambdamodule.h
- modules/lambdamodule/lib/lambdamoduleconfigdata.h
- modules/lambdamodule/lib/lambdamoduleconfiguration.h
- modules/lambdamodule/lib/lambdamodulemeasprogram.cpp
- modules/lambdamodule/lib/lambdamodulemeasprogram.h
* Add overrides / remove unnecessary virtuals
* Remove unused includes / replace forwards
* Remove unused monster enum
> lambdamodule: Tidy up code

- modules/apimodule/lib/CMakeLists.txt
- modules/apimodule/lib/apimodule.cpp
- modules/apimodule/lib/apimodule.h
- modules/apimodule/lib/apimoduleauthorize.cpp
- modules/apimodule/lib/apimoduleauthorize.h
Previous method sill active: for now can use both in parallel.
> Add RPC flow to request new trust.

- modulemanager/app/main.cpp
https://github.com/ZeraGmbH/vf-logger/commit/349f5612646adbd5150c81a1668b52e65bfbb9b0
> main: move logging disabled on session change to vf-logger
