CMakeLists.txt

This change in neccessary because the zera-libsAndServices-metaproject defines
a different project_source_dir.
Signed-off-by: bhamacher <b.hamacher@zera.de>

CMakeLists.txt: changed project_source_dir to current_project_source dir

---

zera-modules/statusmodule/src/statusmoduleinit.cpp
zera-modules/statusmodule/src/statusmoduleinit.h

See commit message for more details.
* Tested with vf-debugger
* To be honest: I have no idea if SCPI access works or if the field name 'DEVTYPE' conflicts with SCPI conventions

statusmodule: add component INF_DeviceType

---

zera-modules/sec1module/src/com5003-sec1module.xml
zera-modules/sec1module/src/com5003-sec1module2.xml
zera-modules/sec1module/src/mt310s2-sec1module.xml
zera-modules/sem1module/src/com5003-sem1module.xml
zera-modules/sem1module/src/mt310s2-sem1module.xml
zera-modules/spm1module/src/com5003-spm1module.xml
zera-modules/spm1module/src/mt310s2-spm1module.xml

COM modules were configured with 2s intervall. That caused confusion in the
transition ARMED -> STARTED.

Reduce interval for all error calculator modules down to 0.5s

---

zera-comm/zera-i2c/CMakeLists.txt
zera-comm/zera-i2c/zerai2cConfig.cmake.in

* zera-i2c needs QtCore only
* popped up on autobuilder: it does not have any Qt dev-packages installed
* test builds on local machine passed: the devel packages are installed there

zera-i2c/CMake: Fix dependencies

---

zera-misc/CMakeLists.txt
zera-misc/zeramiscConfig.cmake.in

* zera-misc needs QtCore only
* popped up on autobuilder: it does not have any Qt dev-packages installed
* test builds on local machine passed: the devel packages are installed there

zera-misc/CMake: Fix dependencies

---

zera-modules/rangemodule/src/adjustment.h

Fell over this while trying to fix wrong adjustement reported on MT310s2

rangemodule: remove unused member variable m_nAdjStatus

---

zera-modules/sec1module/src/sec1modulemeasprogram.cpp
zera-modules/sec1module/src/sec1modulemeasprogram.h

@plohmer: Fixes continuous measurement (see device on my desk) - but please review and let me know what the state m_readIntRegisterState is for: m_nIntReg is written in handler but not used anywhere.

Block ec int longer

---

zera-basemodule/basemodule.cpp
zera-basemodule/basemodule.h
zera-modules/scpimodule/src/com5003-scpimodule.xml
zera-modules/scpimodule/src/ieee488-2.cpp
zera-modules/scpimodule/src/ieee488-2.h
zera-modules/scpimodule/src/mt310s2-scpimodule.xml

* fix Umlaute
* add serialnumber and make use of /opt/zera/conf/serialnumber generated by
zera-setup2
* set fallback values in case of entries missing

scpimodule: Fix *idn? according to John's report

---

zera-comm/zera-proxy/proxyprotobufwrapper.cpp

| <...>/proxyprotobufwrapper.cpp:25: warning: 'ByteSize' is deprecated: Please use ByteSizeLong() instead

Fix deprecation warning

---

zera-modules/sem1module/src/sem1modulemeasprogram.cpp
zera-modules/spm1module/src/spm1modulemeasprogram.cpp

This is a valid use case: A measurement was run and user changes unit.
Currently the units are changes but the error value remains unchanged and is
then incorrect.

sem1module/sep1module: recalc result on unit change at READY state

---

zera-modules/sem1module/src/sem1modulemeasprogram.cpp
zera-modules/spm1module/src/spm1modulemeasprogram.cpp

How embarrising: in
commit 7faa53a1830e786834f46e20bbb0c49addbdf5c2
Author: Andreas Müller <schnitzeltony@gmail.com>
Date:   Tue Dec 15 19:11:06 2020 +0100
SEC/SEM modules: Fix some warnings to be taken seriously
the value
(1<<32) - 2
was replaced by
std::numeric_limits<quint32>::max()
which is different and ruining Start/Stop

Fix Start-/Stop measurement

---

zera-modules/sec1module/src/sec1modulemeasprogram.cpp
zera-modules/sec1module/src/sec1modulemeasprogram.h

We cannot use an accumulated deviation: The mean value changes on every result
and all deviations have to be calculated based on current mean value.

MultiResults: Fix thinko in calculation of standard deviation

---

zera-misc/dspinterface_p.cpp
zera-misc/dspinterface_p.h

Avoid surprises in case a module starts dataacquisition/dspmemoryread in a
syncronous sequence.

dspinterface_p: Keep pointer to data and data type per message

---

zera-modules/rangemodule/src/rangeobsermatic.cpp
zera-modules/rangemodule/src/rangeobsermatic.h

The scaling group is determined using the active alias list now.
Furthermore an attribute was bad named

Enable group use with more than one session

---

zera-modules/oscimodule/src/oscimodule.cpp
zera-modules/oscimodule/src/oscimoduleconfiguration.cpp
zera-modules/oscimodule/src/oscimodulefactory.cpp
zera-modules/oscimodule/src/oscimodulemeasprogram.cpp
zera-modules/oscimodule/src/oscimoduleobservation.cpp

oscimodule: replace Qt4 syntax for signal/slot by Qt5 syntax

---

zera-modules/sourcemodule/deviceinfo/FG4PhaseTest.json

As the name suggests FG4PhaseTest is for test only and has no real life
device. To allow GUI testing as long as there is no harmonics support, allow
harmonics only here.

sourcemodule: Let FG4PhaseTest support harmonics

---

zera-modules/sourcemodule/src/sourceinterface.h

sourceinterface: increase default response timeout

---

zera-comm/zera-i2c/i2cutils.cpp
zera-comm/zera-i2c/i2cutils.h
zera-dev/F24LC256.cpp
zera-dev/F24LC256.h
zera-dev/F24LC256_p.cpp
zera-dev/F24LC256_p.h
zera-dev/i2ceeprom_p.cpp
zera-dev/i2ceeprom_p.h
zera-dev/zera_mcontroller_base.cpp

* output errors unconditionally
* remove info message - logging is client's job

Remove debug level from all i2c related classes to simplify code

---

.github/workflows/buildAndTest.yml
CMakeLists.txt
zera-service-common/CMakeLists.txt
zera-service-common/src/CMakeLists.txt
zera-service-common/src/meas-channels/CMakeLists.txt
zera-service-common/src/meas-channels/justnode.cpp
zera-service-common/src/meas-channels/justnode.h
zera-service-common/src/meas-channels/zerameaschannelsConfig.cmake.in

We take cJustNode from com5003d and mt310s2d with one modification:
cJustNode::Serialize gets a parameter digits. We have to pass this since
* mt310s2d serializes with 6 digits
* com5003d serializes with 8 digits
and we do not want to introduce incompatibilities

Add new library zerameaschannels / add cJustNode

---

zera-modules/scpimodule/src/scpiserver.cpp

m_pSerialClient is in m_SCPIClientList -> We have to call special delete before
deleting all from m_SCPIClientList.

scpimodule: Avoid double deletion on module unload

---

zera-modules/samplemodule/src/com5003-samplemodule.xml
zera-modules/samplemodule/src/mt310s2-samplemodule.xml

samplemodule config com5003 / mt310s2: Set PLL automatic on by default

---

zera-modules-common/service-interfaces/lib/pcbinterface.cpp
zera-modules-common/service-interfaces/lib/pcbinterface.h
zera-modules-common/service-interfaces/lib/pcbinterface_p.cpp
zera-modules-common/service-interfaces/lib/pcbinterface_p.h
zera-modules/adjustmentmodule/src/adjustmentmodulemeasprogram.cpp
zera-modules/adjustmentmodule/src/adjustmentmodulemeasprogram.h
zera-modules/adjustmentmodule/src/adjustvalidator.cpp
zera-modules/scpimodule/src/scpi-clients/scpiclient.cpp

* It causes nothing but confusion
* We were tempted to remove service code either but who knows which odd clients as PZTools might require them

Remove unused cPCBInterface::adjustInit

---

zera-modules-common/zera-basemodule/tests/test_inttohexstringconvert.cpp
zera-modules-common/zera-basemodule/tests/test_phasevalidatorstringgenerator.cpp
zera-modules/adjustmentmodule/tests/test_adj_config_load.cpp
zera-modules/adjustmentmodule/tests/test_adjustmentmoduleactivator.cpp
zera-modules/scpimodule/tests/test_scpi_config_load.cpp
zera-modules/sourcemodule/tests/qtest/test_iotransferdata.cpp
zera-modules/sourcemodule/tests/qtest/test_sourcedevicefacade.cpp
zera-modules/sourcemodule/tests/qtest/test_sourcedevicemanager.cpp
zera-modules/sourcemodule/tests/qtest/test_sourceio.cpp
zera-modules/sourcemodule/tests/qtest/test_sourceperiodicpollerstate.cpp
zera-modules/sourcemodule/tests/qtest/test_sourcescanner.cpp
zera-modules/sourcemodule/tests/qtest/test_sourcestatecontroller.cpp
zera-modules/sourcemodule/tests/qtest/test_sourceswitchjson.cpp
zera-modules/statusmodule/tests/test_status_config_load.cpp

This ';' wasn't needed and was showing a warning on some QtCreator

Remove ';' from QTEST_MAIN()

---

zera-i2c/zera-i2c-devices/lib/mcontroller/zeramcontrollerbootloaderstopper.cpp
zera-modules/modules/sec1module/configs/com5003-sec1module.xml
zera-modules/modules/sec1module/configs/com5003-sec1module2.xml
zera-modules/modules/sec1module/configs/com5003-sec1module3.xml
zera-modules/modules/sec1module/configs/mt310s2-sec1module.xml
zera-modules/modules/sec1module/configs/mt310s2-sec1module_f1f0.xml
zera-modules/modules/sec1module/configs/sec1module.xsd
zera-modules/modules/sec1module/lib/sec1moduleconfigdata.h
zera-modules/modules/sec1module/lib/sec1moduleconfiguration.cpp
zera-modules/modules/sec1module/lib/sec1moduleconfiguration.h

It is not used and we have a single sec1modconfpar:parameter:measure:mode

sec1module: Remove unused/redundant meas mode list

---

zera-modules/modules/scpimodule/lib/interfaceinterface.cpp
zera-modules/modules/scpimodule/lib/scpiinterface.cpp
zera-modules/modules/scpimodule/lib/scpiinterface.h
zera-modules/modules/scpimodule/lib/scpiserver.cpp

* exportSCPIModelXML needs to be fed in with DEVICE tag and it's value
* cSCPI no longer needs scpi-interface name (it was used only for DEVICE tag)

scpiinterface: Follow changes in zera-scpi/cSCPI/exportSCPIModelXML

---

zera-modules/modules/rangemodule/lib/rangeobsermatic.cpp
zera-modules/modules/sec1module/lib/sec1modulemeasprogram.cpp
zera-modules/modules/sem1module/src/sem1modulemeasprogram.cpp
zera-modules/modules/spm1module/src/spm1modulemeasprogram.cpp

Because unit is already included in 'Valid Strings' of the command.

rangeobsermatic: Remove unit info from range selection scpi cmd info

---

modules/modules/power1module/configs/lem_dc/mt310s2-power1module_U1I4.xml
modules/modules/power1module/configs/lem_dc/mt310s2-power1module_U2I4.xml
modules/modules/power1module/configs/lem_dc/mt310s2-power1module_U3I4.xml
modules/modules/power1module/configs/lem_dc/mt310s2-power1module_U4I4.xml

* QREF is not required
* Now that we display measurement mode in range-settings, it might happen that users select QREF which is not intended
This reverts commit 538773f33425874fc92a8a98ea4a2d45723e5792.

Revert "adds config for QREF on mt310s2"

---

modules/modules/sourcemodule/src/module-gluelogic/sourcemoduleprogram.cpp

* Sources are noisy and a rare resource
* Helpful for tests running on machines

sourcemodule: Get demo sources back in non demo mode

---

modules-common/module-validators/intvalidator.cpp

Following scenario: SCPI starts error calculator and the Start/Stop buttons in GUI do not change.

cIntValidator: Make QVariants cannot be casted from outside

---

modules-common/module-tasks/tests/pcb-server/test_taskunregisternotifier.cpp

Check zera-scpi a0250516ed864654a106ea939de2ffbd8d5d9fc8

test_taskunregisternotifier: Fix test after fixing empty parameters

---

modules/modules/sec1module/lib/sec1modulemeasprogram.cpp

CHanging SCPI labels might ruin client applications
This reverts commit 872a7bb29b97c221f8f8d332b83eb7b253b81692.

Revert "sec1modulemeasprogram: Fix command name of DUT unit"

---

.github/workflows/buildCachedAndTest.yml

* If we find a way to share workflows for all repos it is a good idea to distunguish cached form uncached builds
* remove workflow name again
* make sure to download last available

buildAndTest.yml -> buildCachedAndTest.yml

---

modules/modules/lambdamodule/lib/lambdacalcdelegate.h

The lambda configs which do not have 'activepmeasmode' available will use default value of m_activePowerMeasMode.

lambdacalcdelegate: Set default m_activePowerMeasMode to "4LW"

---

modules/sec1module/lib/sec1modulemeasprogram.cpp
modules/sem1module/lib/sem1modulemeasprogram.cpp
modules/spm1module/lib/spm1modulemeasprogram.cpp

* Loads of warnings when moving GUI to 'Energy register' area: | QVariant type change detected on entity 1200 / component ACT_Status: Old int / new uint
* ACT_Status is read only so we can keep quint32
* Question: Why do these occur hundreds of time per second even when no measurement is running?

sec/sem/spm: Avoid QVariant type changes

---

modules/power1module/lib/power1modulemeasprogram.cpp
modules/power1module/lib/power1modulemeasprogram.h
modules/power1module/tests/test-data/dumpActual.json
modules/power1module/tests/test-data/dumpInitial.json

Had a discussion with HuHü: It showed that is not easy to understand where to get power values in EMOB DC sessions from.
The problem is that initially the channel / index link was fix 1/2/3/SUM. Unfortunately we have shipped and cannot change SCPI structure with current design (the-cat-is-out-problem).
So just change the SCPI doc to explain better where to find values.

power1module: Make phase component descriptions more precise

---

modules/rangemodule/lib/adjustment.cpp

inverted phase state was correctly read from config, but initial state was never propagated to the correct place. Only on change

rangemodule/adjustment.cpp: fix persistency, load up with config values

---

modulemanager/testlib/CMakeLists.txt
modulemanager/testlib/modulemanagertestrunner.cpp
modulemanager/testlib/testmodulemanager.cpp

In case we really need mock network let's use vf-tcp-mock-networklib. By that a more fine grained real/mock network configuration can be chosen

Remove leftovers of Zera::vf-tcp-testlib
